spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stockdb?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: 1q2w3e4r
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.stocktest.model
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8080

logging:
  level:
    com.stocktest: DEBUG

kis:
  app-key: PShM1BBjZaTnwrRQhYom6xwufHsBrfkXA6Uv
  app-secret: ryTFkwMMYt8YvYdMJyXOwYktbsN9OL+kc7hCPVPxRrUFvKaMv+ENct+VBuawcMZwqTyZj39ts1zyQINYst/og+JKkGtBdzBopNDoGPKEDZgqyoQZv8b72rxvSrUuYKvoZrwjV2Wb2HZuA99vX7PCuIaeCQeLHcBeZF76ULCqfs2mKYmnNdk=
  base-url: https://openapi.koreainvestment.com:9443
  ws-url: ws://ops.koreainvestment.com:21000

youtube:
  api-key: AIzaSyBqe9TW5nDWPRSKhz7uCwB6LJw3J1VNqZw
